// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjgKNq6l_z-YLfm3l6-GOuUMpas52DDzA',
    appId: '1:355151692649:web:0efbe2747d76fa02fd73f8',
    messagingSenderId: '355151692649',
    projectId: 'cs401-3e77f',
    authDomain: 'cs401-3e77f.firebaseapp.com',
    storageBucket: 'cs401-3e77f.appspot.com',
    measurementId: 'G-DNMPN95LNJ',
    databaseURL: "https://cs401-3e77f-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvJxkdX3_G9WImWD-FAOVUDN_7_gGJeiI',
    appId: '1:355151692649:android:7a995e37bac8d523fd73f8',
    messagingSenderId: '355151692649',
    projectId: 'cs401-3e77f',
    storageBucket: 'cs401-3e77f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARd7iFeGcC7cNV3JxYGByRkILMo5Iz2wY',
    appId: '1:355151692649:ios:d0a4c121bdea0f0ffd73f8',
    messagingSenderId: '355151692649',
    projectId: 'cs401-3e77f',
    storageBucket: 'cs401-3e77f.appspot.com',
    iosBundleId: 'com.example.puebloDelRio',
  );
}
